UPSTREAM: ramoops: fix compile failure on parisc
Fixes this:

  drivers/char/ramoops.c: In function 'ramoops_init':
  drivers/char/ramoops.c:221: error: implicit declaration of function 'IS_ERR'
  drivers/char/ramoops.c:222: error: implicit declaration of function 'PTR_ERR'

If it actually builds on other platforms, it's probably getting
linux/err.h via some other #include.

BUG=chromium-os:12059
TEST=Tested manually, run autotests on both Mario and Alex

Signed-off-by: James Bottomley <JBottomley@Parallels.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 83c1b31794a9e3cb30edabef7e57fbdbe129c5ce)

Change-Id: I94edeaeb9d9bb4c2a9914e5de34f5a66f8a1d9cb
Signed-off-by: Sergiu Iordache <sergiu@chromium.org>
Reviewed-on: http://gerrit.chromium.org/gerrit/5346
Reviewed-by: Mandeep Singh Baines <msb@chromium.org>