wireless/ath6kl: use of module_param requires the inclusion of moduleparam.h
Otheriwse the module.h split up fails like this:

drivers/net/wireless/ath/ath6kl/init.c:27:26: error: expected ')' before 'uint'

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Kalle Valo <kvalo@qca.qualcomm.com>
(cherry picked from commit c6efe578fc5dd02463d2ee20343494da56bdd3a9)

BUG=chrome-os-partner:5925
TEST=build kernel

Change-Id: Ida871f0588d6801fcab572bc39610d0409ec4b09